version: '3'
services:
  document-parser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - API_KEY=${API_KEY}
    restart: always
